# Custom pipeline configuration
pipeline_type: "CUSTOM"
steps:
  - "FETCH"
  - "EXTRACT"
parallel_preprocessing: false
save_intermediate_results: true
output_corpora_label: "Custom Analysis"

fetcher:
  server_base: "https://search.dip.bundestag.de"
  endpoint_spec: "/api/v1/plenarprotokoll"
  params:
    limit: 2
    format: "json"

extraction:
  country: "GERMANY"
  institution: "PARLIAMENT"
  language: "DE"
  protocol_type: "PLENARY"
