# Fetch and Extract only: Get protocols and extract speeches  
pipeline_type: "FETCH"
save_intermediate_results: true
output_corpora_label: "Fetched German Speeches"

fetcher:
  server_base: "https://search.dip.bundestag.de/api/v1"
  endpoint_spec: "plenarprotokoll-text"
  params:
    format: "json"
    apikey: "OSOegLs.PR2lwJ1dwCeje9vTj7FPOt3hvpYKtwKkhw"
    limit:
    wahlperiode: 20
